name: noaa-storm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - matplotlib
  - seaborn
  - statsmodels
  - scipy
  - duckdb
  - requests
  - pyyaml
  - pip
  - pip:
      - python-dotenv
